#!/usr/bin/env bash
set -euo pipefail
repo=$(cd "$(dirname "$0")/.." && pwd); coordinator="$repo/workflow/coordinator"; tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
# shellcheck source=workflow/lib/workflow.sh
source "$repo/workflow/lib/run-paths.sh"; source "$repo/workflow/lib/manifest.sh"; source "$repo/workflow/lib/state.sh"; source "$repo/workflow/lib/workflow.sh"
fail(){ echo "FAIL $*" >&2; exit 1; }
new_run(){ local n=$1 max=${2:-2}; mkdir -p "$tmp/$n/root" "$tmp/$n/w" "$tmp/$n/runs"; echo milestone >"$tmp/$n/m"; git -C "$tmp/$n/w" init -q; git -C "$tmp/$n/w" config user.name t; git -C "$tmp/$n/w" config user.email t@x; echo x >"$tmp/$n/w/a"; git -C "$tmp/$n/w" add a; git -C "$tmp/$n/w" commit -qm x; local base=$(git -C "$tmp/$n/w" rev-parse HEAD); WORKFLOW_RUNS_DIR="$tmp/$n/runs" "$coordinator" create-run --repository-root "$tmp/$n/root" --worktree-path "$tmp/$n/w" --branch x --base-sha "$base" --milestone-file "$tmp/$n/m" --max-fix-attempts "$max"; }
# M4 seam fakes: exercise sequencing/locks without provider or process execution.
workflowRunValidation(){ local _repo=$1 run=$2 attempt=$3; mkdir -p "$run/artifacts/validation" "$run/artifacts/diff"; echo diff >"$run/artifacts/diff/attempt-$attempt.patch"; local outcome=pass; case "${CASE:-}" in validation-timeout) outcome=timeout;; validation-truncation) outcome=fail;; esac; printf '{"outcome":"%s","timed_out":%s,"truncated":%s}\n' "$outcome" "$([ "${CASE:-}" = validation-timeout ] && echo true || echo false)" "$([ "${CASE:-}" = validation-truncation ] && echo true || echo false)" >"$run/artifacts/validation/attempt-$attempt.json"; [ "$outcome" = pass ]; }
workflowRunAgent(){ local _repo=$1 run=$2 role=$3 attempt=$4; echo "$role:$attempt" >>"$LAUNCH_LOG"; mkdir -p "$run/artifacts/agents"; case "${CASE:-}:$role" in reviewer-blocked:reviewer|reviewer-timeout:reviewer|implementer-failure:implementer|fixer-failure:fixer) return 1;; esac; local text; case "$role" in implementer) text=$'IMPLEMENTATION_COMPLETE\n\nChanged:\n- a\n\nValidation requested:\nrepository-tests\n\nKnown limitations:\nnone';; fixer) text=$'FIX_COMPLETE\n\nAddressed findings:\n- f\n\nNot addressed:\n- none\n\nValidation requested:\nrepository-tests';; reviewer) if [ "${CASE:-}" = attempts ] || [ "${CASE:-}" = fixer-failure ] || [ "${CASE:-}" = fixer-contention ]; then text=$'REVIEW_COMPLETE\n\n## Findings\n\n- ID: f\n- Severity: high\n- Location: a:1\n- Evidence: e\n- Requested correction: c\n\n## No findings\n\nfalse\n\n## Remaining uncertainty\n\nnone'; else text=$'REVIEW_COMPLETE\n\n## Findings\n\n- ID: none\n- Severity: none\n- Location: none\n- Evidence: none\n- Requested correction: none\n\n## No findings\n\ntrue\n\n## Remaining uncertainty\n\nnone'; fi;; esac; printf '%s\n' "$text" >"$run/artifacts/agents/$role-$attempt.md"; if [ "${CASE:-}" = fixer-contention ] && [ "$role" = reviewer ]; then local lock; lock=$(workflowWorktreeLockDirectory "$(dirname "$run")" "$(workflowStateField "$run/manifest.json" .worktree_path)"); mkdir -p "$lock"; printf 'foreign\n' >"$lock/run-id"; fi; }
run_case(){ CASE=$1; LAUNCH_LOG="$tmp/$CASE.log"; export CASE LAUNCH_LOG; run=$(new_run "$CASE" "${2:-2}"); set +e; workflowRunV1 "$repo" "$run" 10; rc=$?; set -e; }
# Ambiguous/malformed review artifacts remain invalid.
mkdir -p "$tmp/parse/run/reviews" "$tmp/parse/run/artifacts/agents"; printf '%s\n' $'REVIEW_COMPLETE\n\n## Findings\n\n- ID: finding-1\n\n## No findings\n\ntrue\n\n## Remaining uncertainty\n\nnone' >"$tmp/parse/run/artifacts/agents/reviewer-0.md"; workflowWriteReviewArtifact "$tmp/parse/run" 0 v d "$tmp/parse/run/artifacts/agents/reviewer-0.md"; [ "$(jq -r .parse_valid "$tmp/parse/run/reviews/review-0.json")" = false ] || fail contradictory
printf '%s\n' $'REVIEW_COMPLETE\n\n## Findings\n\nnone\n\n## No findings\n\nunclear\n\n## Remaining uncertainty\n\ntrue' >"$tmp/parse/run/artifacts/agents/reviewer-invalid.md"; workflowWriteReviewArtifact "$tmp/parse/run" 9 v9 d9 "$tmp/parse/run/artifacts/agents/reviewer-invalid.md"; [ "$(jq -r .parse_valid "$tmp/parse/run/reviews/review-9.json")" = false ] || fail invalid-no-findings
printf '%s\n' $'REVIEW_COMPLETE\n\n## Findings\n\n- ID: f1\n- Severity: high\n- Location: a:1\n- Evidence: one\n- Requested correction: fix one\n- ID: f2\n- Severity: medium\n- Location: b:2\n- Evidence: two\n- Requested correction: fix two\n\n## No findings\n\nfalse\n\n## Remaining uncertainty\n\nnone' >"$tmp/parse/run/artifacts/agents/reviewer-1.md"; workflowWriteReviewArtifact "$tmp/parse/run" 1 v1 d1 "$tmp/parse/run/artifacts/agents/reviewer-1.md"; [ "$(jq '.findings | length' "$tmp/parse/run/reviews/review-1.json")" -eq 2 ] || fail multiple-findings
# Validator failures never review; bounded fixes stop at the manifest limit.
for kind in validation-timeout validation-truncation; do run_case "$kind"; [ "$rc" -ne 0 ] || fail "$kind success"; [ "$(jq -r .phase "$run/state.json")" = attempt-limit-reached ] || fail "$kind state"; ! grep -q '^reviewer:' "$LAUNCH_LOG" || fail "$kind reviewed"; [ -f "$run/artifacts/validation/attempt-0.json" ] || fail "$kind artifact"; done
# Reviewer blocked/timeout do not create fixers or ready state.
for kind in reviewer-blocked reviewer-timeout; do run_case "$kind"; [ "$rc" -ne 0 ] || fail "$kind success"; [ "$(jq -r .phase "$run/state.json")" = blocked ] || fail "$kind state"; ! grep -q '^fixer:' "$LAUNCH_LOG" || fail "$kind fixed"; done
# Fixer and implementer failure release their own writer locks and stop downstream stages.
for kind in implementer-failure fixer-failure; do run_case "$kind"; [ "$rc" -ne 0 ] || fail "$kind success"; [ "$(jq -r .phase "$run/state.json")" = blocked ] || fail "$kind state"; lock=$(workflowWorktreeLockDirectory "$(dirname "$run")" "$(workflowStateField "$run/manifest.json" .worktree_path)"); [ ! -e "$lock" ] || fail "$kind stale lock"; done
# Two allowed fixes, then a third finding: no third fixer/writer launch.
run_case attempts 2; [ "$(jq -r .phase "$run/state.json")" = attempt-limit-reached ] || fail limit; [ "$(grep -c '^fixer:' "$LAUNCH_LOG")" -eq 2 ] || fail fixer-count; [ "$(grep -c '^reviewer:' "$LAUNCH_LOG")" -eq 3 ] || fail reviewer-count; grep -F 'Authoritative frozen diff: artifacts/diff/attempt-0.patch' "$run/prompts/reviewer-0.md" >/dev/null || fail frozen-diff-handoff
# A lock acquired by another writer after review blocks Fixer, preserves ownership, and reports.
run_case fixer-contention; [ "$rc" -ne 0 ] || fail fixer-contention-success; [ "$(jq -r .phase "$run/state.json")" = blocked ] || fail fixer-contention-state; [ "$(grep -c '^fixer:' "$LAUNCH_LOG" || true)" -eq 0 ] || fail fixer-contention-launch; lock=$(workflowWorktreeLockDirectory "$(dirname "$run")" "$(workflowStateField "$run/manifest.json" .worktree_path)"); [ "$(<"$lock/run-id")" = foreign ] || fail fixer-contention-owner; [ -f "$run/reports/final.md" ] || fail fixer-contention-report
# Foreign lock blocks before any agent and remains owned by the foreign run.
LAUNCH_LOG="$tmp/contention.log"; export LAUNCH_LOG CASE=''; run=$(new_run contention); lock=$(workflowWorktreeLockDirectory "$(dirname "$run")" "$(workflowStateField "$run/manifest.json" .worktree_path)"); mkdir -p "$lock"; echo foreign >"$lock/run-id"; set +e; workflowRunV1 "$repo" "$run" 10; rc=$?; set -e; [ "$rc" -ne 0 ] && [ "$(jq -r .phase "$run/state.json")" = blocked ] && [ "$(<"$lock/run-id")" = foreign ] && [ ! -s "$LAUNCH_LOG" ] || fail contention
echo 'PASS workflow failure paths'
